### ISSUE TITLE
Support GP3 based storage

### ISSUE THREAD

**Issue by dgibbons** [getstrake/aws-pricing#38]
Would need to have the ability to specify IOPS and throughput.

**Comment by mheffner** [comment]
Hi @dgibbons , thanks for opening the issue. So support for GP3 IOPS was added just recently, you can find the formulas here: https://github.com/mheffner/aws-pricing#ebs-provisioned-iops. However, at the time I didn't realize throughput was a separate vector so I need to expand support for that too. :+1:
