### ISSUE TITLE
Reduce required permissions 

### ISSUE THREAD

**Issue by patrickangeles** [getstrake/aws-pricing#39]
Seems very useful, but the required permissions are a bit steep... does it really need all of these? Would be great to just ask for the minimal set.
<img width="453" alt="Screen Shot 2021-08-12 at 10 43 37 AM" src="https://user-images.githubusercontent.com/135980/129217273-348e4473-d194-42c2-a418-e8e241b67fd8.png">

**Comment by mheffner** [comment]
Hi @patrickangeles

Yes, I believe the way Google auth scopes are setup those are the minimal requirements for this add-on to function. There weren't any scopes added that I did not think had to be included for this to work, but definitely looking for feedback of that is incorrect.

Are any of those in particular ones you are concerned about or have questions for why they are required?

**Comment by patrickangeles** [comment]
Hi @mheffner 

Thanks for the prompt response. I suppose it's the first item that gives me the most pause. I'd like to use it for work-related calculators and I'm not ready to grant blanket permission on all my spreadsheets for a third-party plugin.

**Comment by mheffner** [comment]
@patrickangeles I see, yeah unfortunately for aws-pricing to work it needs to be able to read fields to identify pricing configuration details and then write those results back out. The [auth scopes](https://developers.google.com/sheets/api/guides/authorizing#OAuth2Authorizing) are pretty limited for spreadsheets, it is readonly or not. It will definitely not create or delete spreadsheets, but there does not appear to be a way to select that level of granularity.

**Comment by aryounce** [comment]
We have reduced the required permissions to the absolute minimum in [the new version of the add-on](https://github.com/getstrake/aws-pricing-sheets-addon) that is launching soon.
