### ISSUE TITLE
Pricing look ups fail with DNS ERROR

### ISSUE THREAD

**Issue by mheffner** [getstrake/aws-pricing#46]
It looks like the original pricing information is no longer available at: `https://a0.p.awsstatic.com/pricing/1.0/...`. It has now moved to `https://b0.p.awsstatic.com/pricing/2.0/...` and has a new format. This means that this is currently broken until the backend pricing lookups are moved over to the new format.

**Comment by gnanakeethan** [comment]
Is there any hope that this would be fixed?

**Comment by mheffner** [comment]
Hi @gnanakeethan, I'd like to try and take a look soon at how much work this will be. Unfortunately, I don't have a timeline at the moment.

**Comment by MigaFr** [comment]
:s I use your pricing api a lot of time in a week, it is so usefull, so plz can you see this ?

**Comment by mheffner** [comment]
Hey @MigaFr , yes I appreciate the interest. Unfortunately I don't have a good timetable nor know how large a change this will be. I appreciate your interest though!

**Comment by jordibares** [comment]
We are experiencing the same issue, could this be something you can look at at some point? We have a number of spreadsheets relying on your plugin to get live exchange rates and obviously it would be great to have it working again.
Thanks in advance

**Comment by mheffner** [comment]
Hey @jordibares , thanks for commenting. I'm sorry to hear that this broke your current spreadsheets. As I mentioned earlier, the original breakage comes from the API this was relying on disappearing. It was never a public API so there wasn't a guarantee that it would remain forever, however it did provide the best public pricing API that did not require downloading a hundred MB JSON file.

The AWS pricing pages are now using a new v2 API. This API has some differences, but from what I can glean so far it would be usable as a new backend API for this add on.

Unfortunately, while I have found some time to start moving this over to the new backend API I've hit a wall with changes to the compilation/transpiling steps in Google apps script (#47). I've currently exhausted my debugging time on this so I'm hoping to get some support from the clasp team as to suggestions for next steps: https://github.com/google/clasp/issues/947.

Again, apologies for the breakage here. I'll update this issue if the compilation issues have been resolved and I can move forward on testing against the new API.

**Comment by aryounce** [comment]
Following up on our note from last November, we're testing the restored add-on and will have a full announcement soon. You may see full to partial restoration of the sheet functions where you have the add-on installed, but it may fluctuate a bit until we finalize some of the data for RDS.

For now we're keeping this issue open, but you can check back here for updates and let us know if you see any new problems in your sheets when we're done.

**Comment by shameemshah** [comment]
Is there any hope that this would be fixed?

**Comment by reganbrianpatrick** [comment]
> Is there any hope that this would be fixed?

@shameemshah the original plugin has been fixed with EC2 and EBS functionality. We're working on publishing updates that will restore RDS functionality. If you're having any other issues, please let us know!

**Comment by aryounce** [comment]
@shameemshah We've been testing the fix for the last couple of weeks. Could you confirm that it's working in your Google Sheet?

**Comment by aryounce** [comment]
A new version of this Sheets add-on is launching in the very near future. You can check out the [new Github repo](https://github.com/getstrake/aws-pricing-sheets-addon) for the project while we finish preparing to launch.

We have verified that everything works in the new version and are closing issues in this repo in preparation for the migration.
